# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=pie_unix
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),pie_unix)
  Lab1_config = pie_unix

else ifeq ($(config),pie_windows)
  Lab1_config = pie_windows

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Lab1

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Lab1:
ifneq (,$(Lab1_config))
	@echo "==== Building Lab1 ($(Lab1_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(Lab1_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  pie_unix"
	@echo "  pie_windows"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Lab1"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"